config/routes.rb
Rails.application.routes.draw do

  get 'todos/create'
  resources :tasks do
  resources :todos, only: [:create]
  end
  devise_for :users
  resources :todos, only: [:index]
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :todos, dependent: :destroy
    has_many :users, through: :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :task_id, uniqueness: { scope: :user_id}
end

app/models/user.rb
class User < ApplicationRecord

  has_many :todos, dependent: :destroy
  has_many :tasks, through: :todos
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
    before_action :authenticate_user!, except: [:index]
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    def index
      @tasks = Task.all
    end
  
    
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  
  def create
  @task = Task.find(params[:task_id])
  @todo = Todo.new(task: @task, user: current_user)
    if @todo.save
      redirect_to tasks_path, notice: 'tarea agregada a completada'
    else
      redirect_to tasks_path, alert: 'ingresa como usuario para poder completar'
    end
  end
  
  def index
    @todos = current_user.todos
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= tasks_path%>">HOME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      
        <a class="nav-link" href="<%= todos_path%>">TAREAS COMPLETADAS <span class="sr-only">(current)</span></a>

      </li>
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ingreso
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_user_session_path%>">Ingreso</a>
          <a class="dropdown-item" href="<%= new_user_registration_path%>">Registro</a>
          

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= destroy_user_session_path%>"data-method="DELETE">Salir</a>
        </div>
      </li>
      
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo18list</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render 'layouts/navbar' %>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="jumbotron">
  <h1 class="text-center font-weight-bold" style="font-size: 2.5em">TAREAS DIECIOCHERAS</h1>
</div>
<div class="container-fluid">
  <% @tasks.each do |task| %>
    <div class="col-md-4 col-lg-3 col-sm-12 float-left">
      <div class="card mb-2 mt-2">
        <%= image_tag task.photo, class:'card-img-top' %>
        <div class="card-body">

          <h5 class="card-title text-center"><%= task.name %></h5>
          <%= button_to 'Hacer', task_todos_path(task), class: "btn btn-warning" %>

          
          <a href="#" class="btn btn-primary">Listo</a>
           <a href="#" class="btn btn-danger">No listo</a>
           
            
          
        
            
          
        </div>
        <div class="btn-group align-self-center mb-2">
         
            
              
        </div>
      </div>
    </div>
    <div class="w-100" style="margin-top: 3rem"> </div>
  <% end %>
</div>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/index.html.erb
<h1 class="text-center font-weight-bold" style="font-size: 2.5em">TAREAS COMPLETADASS</h1>


<table>

<%@todos.each do |todo| %>
<tr>
<td><%= todo.task.name %> </td>
<td style="text-align: center; vertical-align: middle;">
<input type="checkbox" name="completed" id="">
</td>
</tr>

<% end %>

</table>